### ISSUE TITLE
tag service action failing due to github auth

### ISSUE THREAD

**Issue by hamdiallam** [ethereum-optimism/infra#60]
**Bug Description**
The tag_service action fails as Github returns a 403 to the bot. 

**Steps to Reproduce**
Run tag service workflow

**Additional context**
Would be nice if tag_tool and tag_service shared code

**Comment by zhwrd** [comment]
@hamdiallam what repo does this refer to?

just ran it in optimism and it worked fine.

**Comment by hamdiallam** [comment]
this repo, tagging proxyd/op-txproxy etc.

There's a fix for it here though: https://github.com/ethereum-optimism/infra/pull/62

**Comment by zhwrd** [comment]
merged, will close for now but re-open if its still failing
